sonar.projectKey=crisisview-front
sonar.projectName=CrisisView Front
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,reports/**,coverage/**,*.tar

sonar.sourceEncoding=UTF-8